// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
)

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets
`

func (q *Queries) CountAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConversations = `-- name: CountConversations :one
SELECT count(*) FROM conversations
`

func (q *Queries) CountConversations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, count(*) AS total FROM generation_jobs GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountJobsByStatusRow
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenTickets = `-- name: CountOpenTickets :one
SELECT count(*) FROM support_tickets WHERE status = 'open'
`

func (q *Queries) CountOpenTickets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTickets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsers = `-- name: ListUsers :many

SELECT id, email, password_hash, full_name, created_at, updated_at, deleted_at, organization_id, avatar_url, email_verified_at, role FROM users WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Suivi global superadmin.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrganizationID,
			&i.AvatarUrl,
			&i.EmailVerifiedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2, updated_at = now() WHERE id = $1 RETURNING id, email, password_hash, full_name, created_at, updated_at, deleted_at, organization_id, avatar_url, email_verified_at, role
`

type SetUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.Role,
	)
	return i, err
}

const sumCreditsConsumed = `-- name: SumCreditsConsumed :one
SELECT COALESCE(sum(credits_consumed), 0)::bigint AS total FROM projects
`

func (q *Queries) SumCreditsConsumed(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumCreditsConsumed)
	var total int64
	err := row.Scan(&total)
	return total, err
}
