// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advertising.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeProviderOperation = `-- name: CompleteProviderOperation :exec
UPDATE provider_operations
SET status = 'completed', external_resource_id = $2, completed_at = now()
WHERE id = $1
`

type CompleteProviderOperationParams struct {
	ID                 string `json:"id"`
	ExternalResourceID string `json:"external_resource_id"`
}

func (q *Queries) CompleteProviderOperation(ctx context.Context, arg CompleteProviderOperationParams) error {
	_, err := q.db.Exec(ctx, completeProviderOperation, arg.ID, arg.ExternalResourceID)
	return err
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
UPDATE oauth_states
SET used_at = now()
WHERE state = $1 AND provider = $2
  AND used_at IS NULL AND expires_at > now()
RETURNING state, user_id, provider, expires_at, used_at
`

type ConsumeOAuthStateParams struct {
	State    string `json:"state"`
	Provider string `json:"provider"`
}

func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, arg.State, arg.Provider)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.Provider,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createAdConnection = `-- name: CreateAdConnection :one
INSERT INTO ad_platform_connections (user_id, provider, status, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at
`

type CreateAdConnectionParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
	Status   string `json:"status"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) CreateAdConnection(ctx context.Context, arg CreateAdConnectionParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, createAdConnection,
		arg.UserID,
		arg.Provider,
		arg.Status,
		arg.Metadata,
	)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdCreative = `-- name: CreateAdCreative :one
INSERT INTO ad_creatives (user_id, connection_id, campaign_id, type, asset_id, headline, primary_text, cta, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, connection_id, campaign_id, type, asset_id, external_creative_id, headline, primary_text, cta, status, metadata, created_at, updated_at
`

type CreateAdCreativeParams struct {
	UserID       string      `json:"user_id"`
	ConnectionID string      `json:"connection_id"`
	CampaignID   pgtype.UUID `json:"campaign_id"`
	Type         string      `json:"type"`
	AssetID      pgtype.UUID `json:"asset_id"`
	Headline     string      `json:"headline"`
	PrimaryText  string      `json:"primary_text"`
	Cta          string      `json:"cta"`
	Status       string      `json:"status"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateAdCreative(ctx context.Context, arg CreateAdCreativeParams) (AdCreative, error) {
	row := q.db.QueryRow(ctx, createAdCreative,
		arg.UserID,
		arg.ConnectionID,
		arg.CampaignID,
		arg.Type,
		arg.AssetID,
		arg.Headline,
		arg.PrimaryText,
		arg.Cta,
		arg.Status,
		arg.Metadata,
	)
	var i AdCreative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.CampaignID,
		&i.Type,
		&i.AssetID,
		&i.ExternalCreativeID,
		&i.Headline,
		&i.PrimaryText,
		&i.Cta,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state, user_id, provider, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateOAuthStateParams struct {
	State     string    `json:"state"`
	UserID    string    `json:"user_id"`
	Provider  string    `json:"provider"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.State,
		arg.UserID,
		arg.Provider,
		arg.ExpiresAt,
	)
	return err
}

const createProviderOperation = `-- name: CreateProviderOperation :one
INSERT INTO provider_operations (user_id, connection_id, provider, operation_type, status, internal_resource_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, connection_id, provider, operation_type, status, attempts, internal_resource_id, external_resource_id, error_code, error_message, created_at, started_at, completed_at
`

type CreateProviderOperationParams struct {
	UserID             string      `json:"user_id"`
	ConnectionID       pgtype.UUID `json:"connection_id"`
	Provider           string      `json:"provider"`
	OperationType      string      `json:"operation_type"`
	Status             string      `json:"status"`
	InternalResourceID string      `json:"internal_resource_id"`
}

func (q *Queries) CreateProviderOperation(ctx context.Context, arg CreateProviderOperationParams) (ProviderOperation, error) {
	row := q.db.QueryRow(ctx, createProviderOperation,
		arg.UserID,
		arg.ConnectionID,
		arg.Provider,
		arg.OperationType,
		arg.Status,
		arg.InternalResourceID,
	)
	var i ProviderOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.Provider,
		&i.OperationType,
		&i.Status,
		&i.Attempts,
		&i.InternalResourceID,
		&i.ExternalResourceID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failProviderOperation = `-- name: FailProviderOperation :exec
UPDATE provider_operations
SET status = 'failed', error_code = $2, error_message = $3, completed_at = now()
WHERE id = $1
`

type FailProviderOperationParams struct {
	ID           string `json:"id"`
	ErrorCode    string `json:"error_code"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) FailProviderOperation(ctx context.Context, arg FailProviderOperationParams) error {
	_, err := q.db.Exec(ctx, failProviderOperation, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	return err
}

const getAdCampaign = `-- name: GetAdCampaign :one
SELECT id, user_id, connection_id, external_campaign_id, name, objective, status, budget_minor, currency, created_at, updated_at FROM ad_campaigns WHERE id = $1 AND user_id = $2
`

type GetAdCampaignParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAdCampaign(ctx context.Context, arg GetAdCampaignParams) (AdCampaign, error) {
	row := q.db.QueryRow(ctx, getAdCampaign, arg.ID, arg.UserID)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.BudgetMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdConnection = `-- name: GetAdConnection :one
SELECT id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at FROM ad_platform_connections WHERE id = $1 AND user_id = $2
`

type GetAdConnectionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAdConnection(ctx context.Context, arg GetAdConnectionParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, getAdConnection, arg.ID, arg.UserID)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdConnectionByProvider = `-- name: GetAdConnectionByProvider :one
SELECT id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at FROM ad_platform_connections WHERE user_id = $1 AND provider = $2
`

type GetAdConnectionByProviderParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetAdConnectionByProvider(ctx context.Context, arg GetAdConnectionByProviderParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, getAdConnectionByProvider, arg.UserID, arg.Provider)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdCreative = `-- name: GetAdCreative :one
SELECT id, user_id, connection_id, campaign_id, type, asset_id, external_creative_id, headline, primary_text, cta, status, metadata, created_at, updated_at FROM ad_creatives WHERE id = $1 AND user_id = $2
`

type GetAdCreativeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAdCreative(ctx context.Context, arg GetAdCreativeParams) (AdCreative, error) {
	row := q.db.QueryRow(ctx, getAdCreative, arg.ID, arg.UserID)
	var i AdCreative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.CampaignID,
		&i.Type,
		&i.AssetID,
		&i.ExternalCreativeID,
		&i.Headline,
		&i.PrimaryText,
		&i.Cta,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderOperation = `-- name: GetProviderOperation :one
SELECT id, user_id, connection_id, provider, operation_type, status, attempts, internal_resource_id, external_resource_id, error_code, error_message, created_at, started_at, completed_at FROM provider_operations WHERE id = $1 AND user_id = $2
`

type GetProviderOperationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetProviderOperation(ctx context.Context, arg GetProviderOperationParams) (ProviderOperation, error) {
	row := q.db.QueryRow(ctx, getProviderOperation, arg.ID, arg.UserID)
	var i ProviderOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.Provider,
		&i.OperationType,
		&i.Status,
		&i.Attempts,
		&i.InternalResourceID,
		&i.ExternalResourceID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAdCampaigns = `-- name: ListAdCampaigns :many
SELECT id, user_id, connection_id, external_campaign_id, name, objective, status, budget_minor, currency, created_at, updated_at FROM ad_campaigns WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAdCampaigns(ctx context.Context, userID string) ([]AdCampaign, error) {
	rows, err := q.db.Query(ctx, listAdCampaigns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdCampaign
	for rows.Next() {
		var i AdCampaign
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.ExternalCampaignID,
			&i.Name,
			&i.Objective,
			&i.Status,
			&i.BudgetMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdCampaignsByConnection = `-- name: ListAdCampaignsByConnection :many
SELECT id, user_id, connection_id, external_campaign_id, name, objective, status, budget_minor, currency, created_at, updated_at FROM ad_campaigns WHERE connection_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAdCampaignsByConnection(ctx context.Context, connectionID string) ([]AdCampaign, error) {
	rows, err := q.db.Query(ctx, listAdCampaignsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdCampaign
	for rows.Next() {
		var i AdCampaign
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.ExternalCampaignID,
			&i.Name,
			&i.Objective,
			&i.Status,
			&i.BudgetMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdConnections = `-- name: ListAdConnections :many
SELECT id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at FROM ad_platform_connections WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAdConnections(ctx context.Context, userID string) ([]AdPlatformConnection, error) {
	rows, err := q.db.Query(ctx, listAdConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdPlatformConnection
	for rows.Next() {
		var i AdPlatformConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Status,
			&i.ExternalUserID,
			&i.ExternalAccountID,
			&i.ExternalAccountName,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.AccessTokenExpiresAt,
			&i.Scopes,
			&i.Metadata,
			&i.LastError,
			&i.LastErrorAt,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdConnectionsByProvider = `-- name: ListAdConnectionsByProvider :many
SELECT id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at FROM ad_platform_connections WHERE provider = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListAdConnectionsByProvider(ctx context.Context, provider string) ([]AdPlatformConnection, error) {
	rows, err := q.db.Query(ctx, listAdConnectionsByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdPlatformConnection
	for rows.Next() {
		var i AdPlatformConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Status,
			&i.ExternalUserID,
			&i.ExternalAccountID,
			&i.ExternalAccountName,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.AccessTokenExpiresAt,
			&i.Scopes,
			&i.Metadata,
			&i.LastError,
			&i.LastErrorAt,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdCreatives = `-- name: ListAdCreatives :many
SELECT id, user_id, connection_id, campaign_id, type, asset_id, external_creative_id, headline, primary_text, cta, status, metadata, created_at, updated_at FROM ad_creatives WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAdCreatives(ctx context.Context, userID string) ([]AdCreative, error) {
	rows, err := q.db.Query(ctx, listAdCreatives, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdCreative
	for rows.Next() {
		var i AdCreative
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.CampaignID,
			&i.Type,
			&i.AssetID,
			&i.ExternalCreativeID,
			&i.Headline,
			&i.PrimaryText,
			&i.Cta,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdInsights = `-- name: ListAdInsights :many
SELECT id, campaign_id, user_id, date, impressions, reach, clicks, spend_minor, conversions, currency, metadata FROM ad_insights
WHERE campaign_id = $1 AND user_id = $2
  AND date >= $3::date AND date <= $4::date
ORDER BY date ASC
`

type ListAdInsightsParams struct {
	CampaignID string      `json:"campaign_id"`
	UserID     string      `json:"user_id"`
	Column3    pgtype.Date `json:"column_3"`
	Column4    pgtype.Date `json:"column_4"`
}

func (q *Queries) ListAdInsights(ctx context.Context, arg ListAdInsightsParams) ([]AdInsight, error) {
	rows, err := q.db.Query(ctx, listAdInsights,
		arg.CampaignID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdInsight
	for rows.Next() {
		var i AdInsight
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.UserID,
			&i.Date,
			&i.Impressions,
			&i.Reach,
			&i.Clicks,
			&i.SpendMinor,
			&i.Conversions,
			&i.Currency,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderOperations = `-- name: ListProviderOperations :many
SELECT id, user_id, connection_id, provider, operation_type, status, attempts, internal_resource_id, external_resource_id, error_code, error_message, created_at, started_at, completed_at FROM provider_operations WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListProviderOperationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListProviderOperations(ctx context.Context, arg ListProviderOperationsParams) ([]ProviderOperation, error) {
	rows, err := q.db.Query(ctx, listProviderOperations, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderOperation
	for rows.Next() {
		var i ProviderOperation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.Provider,
			&i.OperationType,
			&i.Status,
			&i.Attempts,
			&i.InternalResourceID,
			&i.ExternalResourceID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProviderOperationProcessing = `-- name: MarkProviderOperationProcessing :exec
UPDATE provider_operations
SET status = 'processing', started_at = now(), attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkProviderOperationProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markProviderOperationProcessing, id)
	return err
}

const pruneOAuthStates = `-- name: PruneOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) PruneOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneOAuthStates)
	return err
}

const selectAdAccount = `-- name: SelectAdAccount :one
UPDATE ad_platform_connections
SET external_account_id = $3,
    external_account_name = $4,
    metadata = metadata || $5,
    status = 'active',
    updated_at = now()
WHERE id = $2 AND user_id = $1
RETURNING id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at
`

type SelectAdAccountParams struct {
	UserID              string `json:"user_id"`
	ID                  string `json:"id"`
	ExternalAccountID   string `json:"external_account_id"`
	ExternalAccountName string `json:"external_account_name"`
	Metadata            []byte `json:"metadata"`
}

func (q *Queries) SelectAdAccount(ctx context.Context, arg SelectAdAccountParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, selectAdAccount,
		arg.UserID,
		arg.ID,
		arg.ExternalAccountID,
		arg.ExternalAccountName,
		arg.Metadata,
	)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAdConnectionStatus = `-- name: SetAdConnectionStatus :one
UPDATE ad_platform_connections
SET status = $3,
    last_error = $4,
    last_error_at = CASE WHEN $4 <> '' THEN now() ELSE last_error_at END,
    updated_at = now()
WHERE id = $2 AND user_id = $1
RETURNING id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at
`

type SetAdConnectionStatusParams struct {
	UserID    string `json:"user_id"`
	ID        string `json:"id"`
	Status    string `json:"status"`
	LastError string `json:"last_error"`
}

func (q *Queries) SetAdConnectionStatus(ctx context.Context, arg SetAdConnectionStatusParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, setAdConnectionStatus,
		arg.UserID,
		arg.ID,
		arg.Status,
		arg.LastError,
	)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAdConnectionSynced = `-- name: SetAdConnectionSynced :one
UPDATE ad_platform_connections
SET last_sync_at = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at
`

type SetAdConnectionSyncedParams struct {
	ID         string             `json:"id"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
}

func (q *Queries) SetAdConnectionSynced(ctx context.Context, arg SetAdConnectionSyncedParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, setAdConnectionSynced, arg.ID, arg.LastSyncAt)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdCampaign = `-- name: UpdateAdCampaign :one
UPDATE ad_campaigns
SET name = COALESCE(NULLIF($3, ''), name),
    status = COALESCE(NULLIF($4, ''), status),
    budget_minor = COALESCE(NULLIF($5::bigint, 0), budget_minor),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, connection_id, external_campaign_id, name, objective, status, budget_minor, currency, created_at, updated_at
`

type UpdateAdCampaignParams struct {
	ID      string      `json:"id"`
	UserID  string      `json:"user_id"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 int64       `json:"column_5"`
}

func (q *Queries) UpdateAdCampaign(ctx context.Context, arg UpdateAdCampaignParams) (AdCampaign, error) {
	row := q.db.QueryRow(ctx, updateAdCampaign,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.BudgetMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdConnectionTokens = `-- name: UpdateAdConnectionTokens :one
UPDATE ad_platform_connections
SET access_token_enc = $2,
    refresh_token_enc = $3,
    access_token_expires_at = $4,
    external_user_id = $5,
    scopes = $6,
    status = $7,
    last_error = '',
    last_error_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, provider, status, external_user_id, external_account_id, external_account_name, access_token_enc, refresh_token_enc, access_token_expires_at, scopes, metadata, last_error, last_error_at, last_sync_at, created_at, updated_at
`

type UpdateAdConnectionTokensParams struct {
	ID                   string             `json:"id"`
	AccessTokenEnc       string             `json:"access_token_enc"`
	RefreshTokenEnc      string             `json:"refresh_token_enc"`
	AccessTokenExpiresAt pgtype.Timestamptz `json:"access_token_expires_at"`
	ExternalUserID       string             `json:"external_user_id"`
	Scopes               []string           `json:"scopes"`
	Status               string             `json:"status"`
}

func (q *Queries) UpdateAdConnectionTokens(ctx context.Context, arg UpdateAdConnectionTokensParams) (AdPlatformConnection, error) {
	row := q.db.QueryRow(ctx, updateAdConnectionTokens,
		arg.ID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.AccessTokenExpiresAt,
		arg.ExternalUserID,
		arg.Scopes,
		arg.Status,
	)
	var i AdPlatformConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.ExternalAccountID,
		&i.ExternalAccountName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scopes,
		&i.Metadata,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdCreativeExternal = `-- name: UpdateAdCreativeExternal :one
UPDATE ad_creatives
SET external_creative_id = $3, status = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, connection_id, campaign_id, type, asset_id, external_creative_id, headline, primary_text, cta, status, metadata, created_at, updated_at
`

type UpdateAdCreativeExternalParams struct {
	ID                 string `json:"id"`
	UserID             string `json:"user_id"`
	ExternalCreativeID string `json:"external_creative_id"`
	Status             string `json:"status"`
}

func (q *Queries) UpdateAdCreativeExternal(ctx context.Context, arg UpdateAdCreativeExternalParams) (AdCreative, error) {
	row := q.db.QueryRow(ctx, updateAdCreativeExternal,
		arg.ID,
		arg.UserID,
		arg.ExternalCreativeID,
		arg.Status,
	)
	var i AdCreative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.CampaignID,
		&i.Type,
		&i.AssetID,
		&i.ExternalCreativeID,
		&i.Headline,
		&i.PrimaryText,
		&i.Cta,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdCampaign = `-- name: UpsertAdCampaign :one
INSERT INTO ad_campaigns (user_id, connection_id, external_campaign_id, name, objective, status, budget_minor, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (connection_id, external_campaign_id) DO UPDATE
SET name = EXCLUDED.name,
    objective = EXCLUDED.objective,
    status = EXCLUDED.status,
    budget_minor = EXCLUDED.budget_minor,
    currency = EXCLUDED.currency,
    updated_at = now()
RETURNING id, user_id, connection_id, external_campaign_id, name, objective, status, budget_minor, currency, created_at, updated_at
`

type UpsertAdCampaignParams struct {
	UserID             string `json:"user_id"`
	ConnectionID       string `json:"connection_id"`
	ExternalCampaignID string `json:"external_campaign_id"`
	Name               string `json:"name"`
	Objective          string `json:"objective"`
	Status             string `json:"status"`
	BudgetMinor        int64  `json:"budget_minor"`
	Currency           string `json:"currency"`
}

func (q *Queries) UpsertAdCampaign(ctx context.Context, arg UpsertAdCampaignParams) (AdCampaign, error) {
	row := q.db.QueryRow(ctx, upsertAdCampaign,
		arg.UserID,
		arg.ConnectionID,
		arg.ExternalCampaignID,
		arg.Name,
		arg.Objective,
		arg.Status,
		arg.BudgetMinor,
		arg.Currency,
	)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ExternalCampaignID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.BudgetMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdInsight = `-- name: UpsertAdInsight :exec
INSERT INTO ad_insights (campaign_id, user_id, date, impressions, reach, clicks, spend_minor, conversions, currency, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (campaign_id, date) DO UPDATE
SET impressions = EXCLUDED.impressions,
    reach = EXCLUDED.reach,
    clicks = EXCLUDED.clicks,
    spend_minor = EXCLUDED.spend_minor,
    conversions = EXCLUDED.conversions,
    currency = EXCLUDED.currency,
    metadata = EXCLUDED.metadata
`

type UpsertAdInsightParams struct {
	CampaignID  string      `json:"campaign_id"`
	UserID      string      `json:"user_id"`
	Date        pgtype.Date `json:"date"`
	Impressions int64       `json:"impressions"`
	Reach       int64       `json:"reach"`
	Clicks      int64       `json:"clicks"`
	SpendMinor  int64       `json:"spend_minor"`
	Conversions float64     `json:"conversions"`
	Currency    string      `json:"currency"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpsertAdInsight(ctx context.Context, arg UpsertAdInsightParams) error {
	_, err := q.db.Exec(ctx, upsertAdInsight,
		arg.CampaignID,
		arg.UserID,
		arg.Date,
		arg.Impressions,
		arg.Reach,
		arg.Clicks,
		arg.SpendMinor,
		arg.Conversions,
		arg.Currency,
		arg.Metadata,
	)
	return err
}
