// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (user_id, project_id, kind, storage_key, filename, content_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, project_id, kind, storage_key, filename, content_type, size_bytes, created_at
`

type CreateAssetParams struct {
	UserID      string `json:"user_id"`
	ProjectID   string `json:"project_id"`
	Kind        string `json:"kind"`
	StorageKey  string `json:"storage_key"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int32  `json:"size_bytes"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.ProjectID,
		arg.Kind,
		arg.StorageKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, user_id, project_id, kind, storage_key, filename, content_type, size_bytes, created_at FROM assets WHERE id = $1 AND user_id = $2
`

type GetAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.ID, arg.UserID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsByProject = `-- name: ListAssetsByProject :many
SELECT id, user_id, project_id, kind, storage_key, filename, content_type, size_bytes, created_at FROM assets WHERE project_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAssetsByProject(ctx context.Context, projectID string) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Kind,
			&i.StorageKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
