// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::text = '' OR action = $2::text)
  AND ($3::text = '' OR entity = $3::text)
`

type CountAuditLogsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Action string      `json:"action"`
	Entity string      `json:"entity"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.UserID, arg.Action, arg.Entity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, action, entity, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID *string     `json:"entity_id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, entity, entity_id, metadata, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::text = '' OR action = $2::text)
  AND ($3::text = '' OR entity = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Entity    string      `json:"entity"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
