// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, plan_id, amount_minor, currency, provider, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, plan_id, amount_minor, currency, provider, status, idempotency_key, provider_reference, created_at, updated_at, checkout_url
`

type CreatePaymentParams struct {
	UserID         string      `json:"user_id"`
	PlanID         pgtype.UUID `json:"plan_id"`
	AmountMinor    int32       `json:"amount_minor"`
	Currency       string      `json:"currency"`
	Provider       string      `json:"provider"`
	Status         string      `json:"status"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.PlanID,
		arg.AmountMinor,
		arg.Currency,
		arg.Provider,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.AmountMinor,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.IdempotencyKey,
		&i.ProviderReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutUrl,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, plan_id, amount_minor, currency, provider, status, idempotency_key, provider_reference, created_at, updated_at, checkout_url FROM payments WHERE id = $1 AND user_id = $2
`

type GetPaymentParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.ID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.AmountMinor,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.IdempotencyKey,
		&i.ProviderReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutUrl,
	)
	return i, err
}

const getPaymentByProviderReference = `-- name: GetPaymentByProviderReference :one
SELECT id, user_id, plan_id, amount_minor, currency, provider, status, idempotency_key, provider_reference, created_at, updated_at, checkout_url FROM payments WHERE provider_reference = $1 LIMIT 1
`

func (q *Queries) GetPaymentByProviderReference(ctx context.Context, providerReference *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderReference, providerReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.AmountMinor,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.IdempotencyKey,
		&i.ProviderReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutUrl,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, credits, price_minor, currency, sort_order, is_active, created_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credits,
		&i.PriceMinor,
		&i.Currency,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, name, credits, price_minor, currency, sort_order, is_active, created_at FROM plans WHERE is_active = true ORDER BY sort_order ASC
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Credits,
			&i.PriceMinor,
			&i.Currency,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT id, user_id, plan_id, amount_minor, currency, provider, status, idempotency_key, provider_reference, created_at, updated_at, checkout_url FROM payments WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListPaymentsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.AmountMinor,
			&i.Currency,
			&i.Provider,
			&i.Status,
			&i.IdempotencyKey,
			&i.ProviderReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CheckoutUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentStatus = `-- name: MarkPaymentStatus :one
UPDATE payments
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, amount_minor, currency, provider, status, idempotency_key, provider_reference, created_at, updated_at, checkout_url
`

type MarkPaymentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) MarkPaymentStatus(ctx context.Context, arg MarkPaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.AmountMinor,
		&i.Currency,
		&i.Provider,
		&i.Status,
		&i.IdempotencyKey,
		&i.ProviderReference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutUrl,
	)
	return i, err
}

const updatePaymentCheckout = `-- name: UpdatePaymentCheckout :exec
UPDATE payments
SET provider_reference = $2, checkout_url = $3, updated_at = now()
WHERE id = $1
`

type UpdatePaymentCheckoutParams struct {
	ID                string  `json:"id"`
	ProviderReference *string `json:"provider_reference"`
	CheckoutUrl       *string `json:"checkout_url"`
}

func (q *Queries) UpdatePaymentCheckout(ctx context.Context, arg UpdatePaymentCheckoutParams) error {
	_, err := q.db.Exec(ctx, updatePaymentCheckout, arg.ID, arg.ProviderReference, arg.CheckoutUrl)
	return err
}
