// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCommerceConnection = `-- name: DeleteCommerceConnection :exec
DELETE FROM commerce_connections WHERE id = $1 AND user_id = $2
`

type DeleteCommerceConnectionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCommerceConnection(ctx context.Context, arg DeleteCommerceConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteCommerceConnection, arg.ID, arg.UserID)
	return err
}

const deleteCommerceProductLink = `-- name: DeleteCommerceProductLink :exec
DELETE FROM commerce_product_links WHERE id = $1 AND user_id = $2
`

type DeleteCommerceProductLinkParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCommerceProductLink(ctx context.Context, arg DeleteCommerceProductLinkParams) error {
	_, err := q.db.Exec(ctx, deleteCommerceProductLink, arg.ID, arg.UserID)
	return err
}

const deleteCommerceProductLinksByProject = `-- name: DeleteCommerceProductLinksByProject :exec
DELETE FROM commerce_product_links WHERE user_id = $1 AND project_id = $2
`

type DeleteCommerceProductLinksByProjectParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteCommerceProductLinksByProject(ctx context.Context, arg DeleteCommerceProductLinksByProjectParams) error {
	_, err := q.db.Exec(ctx, deleteCommerceProductLinksByProject, arg.UserID, arg.ProjectID)
	return err
}

const getCommerceConnection = `-- name: GetCommerceConnection :one
SELECT id, user_id, provider, status, api_key_enc, webhook_secret_enc, external_store_id, store_name, store_url, store_currency, last_error, last_error_at, last_sync_at, connected_at, created_at, updated_at FROM commerce_connections WHERE user_id = $1 AND provider = $2
`

type GetCommerceConnectionParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetCommerceConnection(ctx context.Context, arg GetCommerceConnectionParams) (CommerceConnection, error) {
	row := q.db.QueryRow(ctx, getCommerceConnection, arg.UserID, arg.Provider)
	var i CommerceConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ApiKeyEnc,
		&i.WebhookSecretEnc,
		&i.ExternalStoreID,
		&i.StoreName,
		&i.StoreUrl,
		&i.StoreCurrency,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceConnectionByStoreID = `-- name: GetCommerceConnectionByStoreID :one
SELECT id, user_id, provider, status, api_key_enc, webhook_secret_enc, external_store_id, store_name, store_url, store_currency, last_error, last_error_at, last_sync_at, connected_at, created_at, updated_at FROM commerce_connections
WHERE external_store_id = $1 AND provider = 'chariow'
LIMIT 1
`

func (q *Queries) GetCommerceConnectionByStoreID(ctx context.Context, externalStoreID string) (CommerceConnection, error) {
	row := q.db.QueryRow(ctx, getCommerceConnectionByStoreID, externalStoreID)
	var i CommerceConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ApiKeyEnc,
		&i.WebhookSecretEnc,
		&i.ExternalStoreID,
		&i.StoreName,
		&i.StoreUrl,
		&i.StoreCurrency,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastSyncAt,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductLink = `-- name: GetCommerceProductLink :one
SELECT id, user_id, connection_id, project_id, external_product_id, external_product_slug, external_product_name, price_minor, currency, status, is_public, public_token, created_at, updated_at FROM commerce_product_links WHERE id = $1 AND user_id = $2
`

type GetCommerceProductLinkParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetCommerceProductLink(ctx context.Context, arg GetCommerceProductLinkParams) (CommerceProductLink, error) {
	row := q.db.QueryRow(ctx, getCommerceProductLink, arg.ID, arg.UserID)
	var i CommerceProductLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProjectID,
		&i.ExternalProductID,
		&i.ExternalProductSlug,
		&i.ExternalProductName,
		&i.PriceMinor,
		&i.Currency,
		&i.Status,
		&i.IsPublic,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductLinkByExternal = `-- name: GetCommerceProductLinkByExternal :one
SELECT id, user_id, connection_id, project_id, external_product_id, external_product_slug, external_product_name, price_minor, currency, status, is_public, public_token, created_at, updated_at FROM commerce_product_links
WHERE connection_id = $1 AND external_product_id = $2
`

type GetCommerceProductLinkByExternalParams struct {
	ConnectionID      string `json:"connection_id"`
	ExternalProductID string `json:"external_product_id"`
}

func (q *Queries) GetCommerceProductLinkByExternal(ctx context.Context, arg GetCommerceProductLinkByExternalParams) (CommerceProductLink, error) {
	row := q.db.QueryRow(ctx, getCommerceProductLinkByExternal, arg.ConnectionID, arg.ExternalProductID)
	var i CommerceProductLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProjectID,
		&i.ExternalProductID,
		&i.ExternalProductSlug,
		&i.ExternalProductName,
		&i.PriceMinor,
		&i.Currency,
		&i.Status,
		&i.IsPublic,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductLinkByProject = `-- name: GetCommerceProductLinkByProject :one
SELECT id, user_id, connection_id, project_id, external_product_id, external_product_slug, external_product_name, price_minor, currency, status, is_public, public_token, created_at, updated_at FROM commerce_product_links
WHERE user_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetCommerceProductLinkByProjectParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetCommerceProductLinkByProject(ctx context.Context, arg GetCommerceProductLinkByProjectParams) (CommerceProductLink, error) {
	row := q.db.QueryRow(ctx, getCommerceProductLinkByProject, arg.UserID, arg.ProjectID)
	var i CommerceProductLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProjectID,
		&i.ExternalProductID,
		&i.ExternalProductSlug,
		&i.ExternalProductName,
		&i.PriceMinor,
		&i.Currency,
		&i.Status,
		&i.IsPublic,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceProductLinkByToken = `-- name: GetCommerceProductLinkByToken :one
SELECT id, user_id, connection_id, project_id, external_product_id, external_product_slug, external_product_name, price_minor, currency, status, is_public, public_token, created_at, updated_at FROM commerce_product_links WHERE public_token = $1 AND is_public = true
`

func (q *Queries) GetCommerceProductLinkByToken(ctx context.Context, publicToken string) (CommerceProductLink, error) {
	row := q.db.QueryRow(ctx, getCommerceProductLinkByToken, publicToken)
	var i CommerceProductLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProjectID,
		&i.ExternalProductID,
		&i.ExternalProductSlug,
		&i.ExternalProductName,
		&i.PriceMinor,
		&i.Currency,
		&i.Status,
		&i.IsPublic,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceSaleByExternalID = `-- name: GetCommerceSaleByExternalID :one
SELECT id, user_id, connection_id, product_link_id, external_sale_id, status, amount_minor, currency, buyer_email, buyer_name, checkout_url, custom_metadata, payload, created_at, updated_at, completed_at FROM commerce_sales
WHERE connection_id = $1 AND external_sale_id = $2
`

type GetCommerceSaleByExternalIDParams struct {
	ConnectionID   string `json:"connection_id"`
	ExternalSaleID string `json:"external_sale_id"`
}

func (q *Queries) GetCommerceSaleByExternalID(ctx context.Context, arg GetCommerceSaleByExternalIDParams) (CommerceSale, error) {
	row := q.db.QueryRow(ctx, getCommerceSaleByExternalID, arg.ConnectionID, arg.ExternalSaleID)
	var i CommerceSale
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProductLinkID,
		&i.ExternalSaleID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.CheckoutUrl,
		&i.CustomMetadata,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertCommerceWebhookEvent = `-- name: InsertCommerceWebhookEvent :one
INSERT INTO commerce_webhook_events
    (user_id, provider, external_pulse_id, external_delivery_id, event_type, payload, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, external_delivery_id) DO NOTHING
RETURNING id, user_id, provider, external_pulse_id, external_delivery_id, event_type, payload, status, created_at
`

type InsertCommerceWebhookEventParams struct {
	UserID             string `json:"user_id"`
	Provider           string `json:"provider"`
	ExternalPulseID    string `json:"external_pulse_id"`
	ExternalDeliveryID string `json:"external_delivery_id"`
	EventType          string `json:"event_type"`
	Payload            []byte `json:"payload"`
	Status             string `json:"status"`
}

func (q *Queries) InsertCommerceWebhookEvent(ctx context.Context, arg InsertCommerceWebhookEventParams) (CommerceWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertCommerceWebhookEvent,
		arg.UserID,
		arg.Provider,
		arg.ExternalPulseID,
		arg.ExternalDeliveryID,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i CommerceWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalPulseID,
		&i.ExternalDeliveryID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCommerceConnections = `-- name: ListCommerceConnections :many
SELECT id, user_id, provider, status, api_key_enc, webhook_secret_enc, external_store_id, store_name, store_url, store_currency, last_error, last_error_at, last_sync_at, connected_at, created_at, updated_at FROM commerce_connections WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCommerceConnections(ctx context.Context, userID string) ([]CommerceConnection, error) {
	rows, err := q.db.Query(ctx, listCommerceConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceConnection
	for rows.Next() {
		var i CommerceConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Status,
			&i.ApiKeyEnc,
			&i.WebhookSecretEnc,
			&i.ExternalStoreID,
			&i.StoreName,
			&i.StoreUrl,
			&i.StoreCurrency,
			&i.LastError,
			&i.LastErrorAt,
			&i.LastSyncAt,
			&i.ConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommerceProductLinks = `-- name: ListCommerceProductLinks :many
SELECT id, user_id, connection_id, project_id, external_product_id, external_product_slug, external_product_name, price_minor, currency, status, is_public, public_token, created_at, updated_at FROM commerce_product_links
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCommerceProductLinks(ctx context.Context, userID string) ([]CommerceProductLink, error) {
	rows, err := q.db.Query(ctx, listCommerceProductLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceProductLink
	for rows.Next() {
		var i CommerceProductLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.ProjectID,
			&i.ExternalProductID,
			&i.ExternalProductSlug,
			&i.ExternalProductName,
			&i.PriceMinor,
			&i.Currency,
			&i.Status,
			&i.IsPublic,
			&i.PublicToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommerceSalesByProductLink = `-- name: ListCommerceSalesByProductLink :many
SELECT id, user_id, connection_id, product_link_id, external_sale_id, status, amount_minor, currency, buyer_email, buyer_name, checkout_url, custom_metadata, payload, created_at, updated_at, completed_at FROM commerce_sales
WHERE product_link_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListCommerceSalesByProductLinkParams struct {
	ProductLinkID pgtype.UUID `json:"product_link_id"`
	UserID        string      `json:"user_id"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) ListCommerceSalesByProductLink(ctx context.Context, arg ListCommerceSalesByProductLinkParams) ([]CommerceSale, error) {
	rows, err := q.db.Query(ctx, listCommerceSalesByProductLink, arg.ProductLinkID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceSale
	for rows.Next() {
		var i CommerceSale
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.ProductLinkID,
			&i.ExternalSaleID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.BuyerEmail,
			&i.BuyerName,
			&i.CheckoutUrl,
			&i.CustomMetadata,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommerceSalesByUser = `-- name: ListCommerceSalesByUser :many
SELECT id, user_id, connection_id, product_link_id, external_sale_id, status, amount_minor, currency, buyer_email, buyer_name, checkout_url, custom_metadata, payload, created_at, updated_at, completed_at FROM commerce_sales
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCommerceSalesByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListCommerceSalesByUser(ctx context.Context, arg ListCommerceSalesByUserParams) ([]CommerceSale, error) {
	rows, err := q.db.Query(ctx, listCommerceSalesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceSale
	for rows.Next() {
		var i CommerceSale
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.ProductLinkID,
			&i.ExternalSaleID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.BuyerEmail,
			&i.BuyerName,
			&i.CheckoutUrl,
			&i.CustomMetadata,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommerceConnectionState = `-- name: UpdateCommerceConnectionState :exec
UPDATE commerce_connections SET
    status = $3,
    last_error = $4,
    last_error_at = CASE WHEN $4 <> '' THEN now() ELSE last_error_at END,
    last_sync_at = $5,
    connected_at = $6,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateCommerceConnectionStateParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Status      string             `json:"status"`
	LastError   string             `json:"last_error"`
	LastSyncAt  pgtype.Timestamptz `json:"last_sync_at"`
	ConnectedAt pgtype.Timestamptz `json:"connected_at"`
}

func (q *Queries) UpdateCommerceConnectionState(ctx context.Context, arg UpdateCommerceConnectionStateParams) error {
	_, err := q.db.Exec(ctx, updateCommerceConnectionState,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.LastError,
		arg.LastSyncAt,
		arg.ConnectedAt,
	)
	return err
}

const updateCommerceProductLinkPublic = `-- name: UpdateCommerceProductLinkPublic :exec
UPDATE commerce_product_links SET
    is_public = $3,
    public_token = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateCommerceProductLinkPublicParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	IsPublic    bool   `json:"is_public"`
	PublicToken string `json:"public_token"`
}

func (q *Queries) UpdateCommerceProductLinkPublic(ctx context.Context, arg UpdateCommerceProductLinkPublicParams) error {
	_, err := q.db.Exec(ctx, updateCommerceProductLinkPublic,
		arg.ID,
		arg.UserID,
		arg.IsPublic,
		arg.PublicToken,
	)
	return err
}

const upsertCommerceConnection = `-- name: UpsertCommerceConnection :exec
INSERT INTO commerce_connections
    (user_id, provider, status, api_key_enc, webhook_secret_enc,
     external_store_id, store_name, store_url, store_currency, connected_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, provider) DO UPDATE SET
    status = excluded.status,
    api_key_enc = excluded.api_key_enc,
    webhook_secret_enc = excluded.webhook_secret_enc,
    external_store_id = excluded.external_store_id,
    store_name = excluded.store_name,
    store_url = excluded.store_url,
    store_currency = excluded.store_currency,
    connected_at = excluded.connected_at,
    updated_at = now()
`

type UpsertCommerceConnectionParams struct {
	UserID           string             `json:"user_id"`
	Provider         string             `json:"provider"`
	Status           string             `json:"status"`
	ApiKeyEnc        string             `json:"api_key_enc"`
	WebhookSecretEnc string             `json:"webhook_secret_enc"`
	ExternalStoreID  string             `json:"external_store_id"`
	StoreName        string             `json:"store_name"`
	StoreUrl         string             `json:"store_url"`
	StoreCurrency    string             `json:"store_currency"`
	ConnectedAt      pgtype.Timestamptz `json:"connected_at"`
}

func (q *Queries) UpsertCommerceConnection(ctx context.Context, arg UpsertCommerceConnectionParams) error {
	_, err := q.db.Exec(ctx, upsertCommerceConnection,
		arg.UserID,
		arg.Provider,
		arg.Status,
		arg.ApiKeyEnc,
		arg.WebhookSecretEnc,
		arg.ExternalStoreID,
		arg.StoreName,
		arg.StoreUrl,
		arg.StoreCurrency,
		arg.ConnectedAt,
	)
	return err
}

const upsertCommerceProductLink = `-- name: UpsertCommerceProductLink :one
INSERT INTO commerce_product_links
    (user_id, connection_id, project_id, external_product_id, external_product_slug,
     external_product_name, price_minor, currency, status, is_public, public_token)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (connection_id, external_product_id) DO UPDATE SET
    user_id = excluded.user_id,
    project_id = excluded.project_id,
    external_product_slug = excluded.external_product_slug,
    external_product_name = excluded.external_product_name,
    price_minor = excluded.price_minor,
    currency = excluded.currency,
    status = excluded.status,
    is_public = excluded.is_public,
    public_token = excluded.public_token,
    updated_at = now()
RETURNING id, user_id, connection_id, project_id, external_product_id, external_product_slug, external_product_name, price_minor, currency, status, is_public, public_token, created_at, updated_at
`

type UpsertCommerceProductLinkParams struct {
	UserID              string `json:"user_id"`
	ConnectionID        string `json:"connection_id"`
	ProjectID           string `json:"project_id"`
	ExternalProductID   string `json:"external_product_id"`
	ExternalProductSlug string `json:"external_product_slug"`
	ExternalProductName string `json:"external_product_name"`
	PriceMinor          int64  `json:"price_minor"`
	Currency            string `json:"currency"`
	Status              string `json:"status"`
	IsPublic            bool   `json:"is_public"`
	PublicToken         string `json:"public_token"`
}

func (q *Queries) UpsertCommerceProductLink(ctx context.Context, arg UpsertCommerceProductLinkParams) (CommerceProductLink, error) {
	row := q.db.QueryRow(ctx, upsertCommerceProductLink,
		arg.UserID,
		arg.ConnectionID,
		arg.ProjectID,
		arg.ExternalProductID,
		arg.ExternalProductSlug,
		arg.ExternalProductName,
		arg.PriceMinor,
		arg.Currency,
		arg.Status,
		arg.IsPublic,
		arg.PublicToken,
	)
	var i CommerceProductLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProjectID,
		&i.ExternalProductID,
		&i.ExternalProductSlug,
		&i.ExternalProductName,
		&i.PriceMinor,
		&i.Currency,
		&i.Status,
		&i.IsPublic,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCommerceSale = `-- name: UpsertCommerceSale :one
INSERT INTO commerce_sales
    (user_id, connection_id, product_link_id, external_sale_id, status,
     amount_minor, currency, buyer_email, buyer_name, checkout_url,
     custom_metadata, payload, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (connection_id, external_sale_id) DO UPDATE SET
    status = excluded.status,
    amount_minor = excluded.amount_minor,
    currency = excluded.currency,
    buyer_email = excluded.buyer_email,
    buyer_name = excluded.buyer_name,
    -- On préserve le checkout_url/metadata/payload existants si l'upsert
    -- (ex. sync) n'en apporte pas (ne jamais effacer l'URL de paiement).
    checkout_url = CASE WHEN excluded.checkout_url <> '' THEN excluded.checkout_url ELSE commerce_sales.checkout_url END,
    custom_metadata = CASE WHEN excluded.custom_metadata = '{}'::jsonb THEN commerce_sales.custom_metadata ELSE excluded.custom_metadata END,
    payload = CASE WHEN excluded.payload = '{}'::jsonb THEN commerce_sales.payload ELSE excluded.payload END,
    completed_at = excluded.completed_at,
    updated_at = now()
RETURNING id, user_id, connection_id, product_link_id, external_sale_id, status, amount_minor, currency, buyer_email, buyer_name, checkout_url, custom_metadata, payload, created_at, updated_at, completed_at
`

type UpsertCommerceSaleParams struct {
	UserID         string             `json:"user_id"`
	ConnectionID   string             `json:"connection_id"`
	ProductLinkID  pgtype.UUID        `json:"product_link_id"`
	ExternalSaleID string             `json:"external_sale_id"`
	Status         string             `json:"status"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	BuyerEmail     string             `json:"buyer_email"`
	BuyerName      string             `json:"buyer_name"`
	CheckoutUrl    string             `json:"checkout_url"`
	CustomMetadata []byte             `json:"custom_metadata"`
	Payload        []byte             `json:"payload"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpsertCommerceSale(ctx context.Context, arg UpsertCommerceSaleParams) (CommerceSale, error) {
	row := q.db.QueryRow(ctx, upsertCommerceSale,
		arg.UserID,
		arg.ConnectionID,
		arg.ProductLinkID,
		arg.ExternalSaleID,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.BuyerEmail,
		arg.BuyerName,
		arg.CheckoutUrl,
		arg.CustomMetadata,
		arg.Payload,
		arg.CompletedAt,
	)
	var i CommerceSale
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.ProductLinkID,
		&i.ExternalSaleID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.CheckoutUrl,
		&i.CustomMetadata,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
