// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id)
VALUES ($1)
RETURNING id, user_id, title, status, opportunity_id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, userID string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, userID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.OpportunityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConversationMessage = `-- name: CreateConversationMessage :one
INSERT INTO conversation_messages (id, conversation_id, user_id, role, content, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, user_id, role, content, payload, created_at
`

type CreateConversationMessageParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	Role           string `json:"role"`
	Content        string `json:"content"`
	Payload        []byte `json:"payload"`
}

func (q *Queries) CreateConversationMessage(ctx context.Context, arg CreateConversationMessageParams) (ConversationMessage, error) {
	row := q.db.QueryRow(ctx, createConversationMessage,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.Payload,
	)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, status, opportunity_id, created_at, updated_at FROM conversations WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.OpportunityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, user_id, role, content, payload, created_at FROM conversation_messages WHERE conversation_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListConversationMessages(ctx context.Context, conversationID string) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMessage
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, status, opportunity_id, created_at, updated_at FROM conversations WHERE user_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListConversationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.OpportunityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdeasByConversation = `-- name: ListIdeasByConversation :many
SELECT id, user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle, is_selected, created_at, hook, explanation, status, updated_at, conversation_id FROM product_ideas WHERE user_id = $1 AND conversation_id = $2 ORDER BY created_at ASC
`

type ListIdeasByConversationParams struct {
	UserID         string      `json:"user_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) ListIdeasByConversation(ctx context.Context, arg ListIdeasByConversationParams) ([]ProductIdea, error) {
	rows, err := q.db.Query(ctx, listIdeasByConversation, arg.UserID, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductIdea
	for rows.Next() {
		var i ProductIdea
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpportunityID,
			&i.Title,
			&i.Subtitle,
			&i.Audience,
			&i.Problem,
			&i.Promise,
			&i.Format,
			&i.EstimatedPrice,
			&i.Difficulty,
			&i.MarketEvidence,
			&i.WhyNow,
			&i.CompetitiveAngle,
			&i.IsSelected,
			&i.CreatedAt,
			&i.Hook,
			&i.Explanation,
			&i.Status,
			&i.UpdatedAt,
			&i.ConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationOpportunity = `-- name: SetConversationOpportunity :one
UPDATE conversations SET opportunity_id = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, title, status, opportunity_id, created_at, updated_at
`

type SetConversationOpportunityParams struct {
	ID            string      `json:"id"`
	OpportunityID pgtype.UUID `json:"opportunity_id"`
}

func (q *Queries) SetConversationOpportunity(ctx context.Context, arg SetConversationOpportunityParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationOpportunity, arg.ID, arg.OpportunityID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.OpportunityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConversationTitle = `-- name: SetConversationTitle :one
UPDATE conversations SET title = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, title, status, opportunity_id, created_at, updated_at
`

type SetConversationTitleParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationTitle, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.OpportunityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchConversation = `-- name: TouchConversation :one
UPDATE conversations SET updated_at = now() WHERE id = $1 RETURNING id, user_id, title, status, opportunity_id, created_at, updated_at
`

func (q *Queries) TouchConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRow(ctx, touchConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.OpportunityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
