// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"
)

const listEnabledPaymentCountries = `-- name: ListEnabledPaymentCountries :many
SELECT code, name, currency, enabled, created_at, updated_at
FROM payment_countries
WHERE enabled = true
ORDER BY name ASC
`

func (q *Queries) ListEnabledPaymentCountries(ctx context.Context) ([]PaymentCountry, error) {
	rows, err := q.db.Query(ctx, listEnabledPaymentCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentCountry
	for rows.Next() {
		var i PaymentCountry
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Currency,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentCountries = `-- name: ListPaymentCountries :many
SELECT code, name, currency, enabled, created_at, updated_at
FROM payment_countries
ORDER BY name ASC
`

func (q *Queries) ListPaymentCountries(ctx context.Context) ([]PaymentCountry, error) {
	rows, err := q.db.Query(ctx, listPaymentCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentCountry
	for rows.Next() {
		var i PaymentCountry
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Currency,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentCountryEnabled = `-- name: SetPaymentCountryEnabled :exec
UPDATE payment_countries
SET enabled = $2, updated_at = now()
WHERE code = $1
`

type SetPaymentCountryEnabledParams struct {
	Code    string `json:"code"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetPaymentCountryEnabled(ctx context.Context, arg SetPaymentCountryEnabledParams) error {
	_, err := q.db.Exec(ctx, setPaymentCountryEnabled, arg.Code, arg.Enabled)
	return err
}
