// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credits.sql

package db

import (
	"context"
	"time"
)

const addCredits = `-- name: AddCredits :one
UPDATE credit_accounts
SET balance = balance + $2, version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, user_id, balance, reserved, version, created_at, updated_at
`

type AddCreditsParams struct {
	ID      string `json:"id"`
	Balance int32  `json:"balance"`
}

func (q *Queries) AddCredits(ctx context.Context, arg AddCreditsParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, addCredits, arg.ID, arg.Balance)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addReserved = `-- name: AddReserved :one
UPDATE credit_accounts
SET reserved = reserved + $2, version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, user_id, balance, reserved, version, created_at, updated_at
`

type AddReservedParams struct {
	ID       string `json:"id"`
	Reserved int32  `json:"reserved"`
}

func (q *Queries) AddReserved(ctx context.Context, arg AddReservedParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, addReserved, arg.ID, arg.Reserved)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCreditTransactions = `-- name: CountCreditTransactions :one
SELECT count(*) FROM credit_transactions
WHERE account_id = $1
  AND ($2::text = '' OR type = $2::text)
  AND ($3::text = '' OR operation = $3::text)
`

type CountCreditTransactionsParams struct {
	AccountID       string `json:"account_id"`
	TypeFilter      string `json:"type_filter"`
	OperationFilter string `json:"operation_filter"`
}

func (q *Queries) CountCreditTransactions(ctx context.Context, arg CountCreditTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditTransactions, arg.AccountID, arg.TypeFilter, arg.OperationFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreditAccount = `-- name: CreateCreditAccount :one
INSERT INTO credit_accounts (user_id, balance)
VALUES ($1, $2)
RETURNING id, user_id, balance, reserved, version, created_at, updated_at
`

type CreateCreditAccountParams struct {
	UserID  string `json:"user_id"`
	Balance int32  `json:"balance"`
}

func (q *Queries) CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, createCreditAccount, arg.UserID, arg.Balance)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditReservation = `-- name: CreateCreditReservation :one
INSERT INTO credit_reservations (account_id, amount, operation, reference, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, amount, operation, reference, status, expires_at, created_at, updated_at
`

type CreateCreditReservationParams struct {
	AccountID string    `json:"account_id"`
	Amount    int32     `json:"amount"`
	Operation string    `json:"operation"`
	Reference string    `json:"reference"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateCreditReservation(ctx context.Context, arg CreateCreditReservationParams) (CreditReservation, error) {
	row := q.db.QueryRow(ctx, createCreditReservation,
		arg.AccountID,
		arg.Amount,
		arg.Operation,
		arg.Reference,
		arg.ExpiresAt,
	)
	var i CreditReservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Operation,
		&i.Reference,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditTransaction = `-- name: CreateCreditTransaction :one
INSERT INTO credit_transactions (account_id, type, amount, operation, reference, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, type, amount, operation, status, reference, metadata, created_at
`

type CreateCreditTransactionParams struct {
	AccountID string  `json:"account_id"`
	Type      string  `json:"type"`
	Amount    int32   `json:"amount"`
	Operation string  `json:"operation"`
	Reference *string `json:"reference"`
	Metadata  []byte  `json:"metadata"`
}

func (q *Queries) CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error) {
	row := q.db.QueryRow(ctx, createCreditTransaction,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.Operation,
		arg.Reference,
		arg.Metadata,
	)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Operation,
		&i.Status,
		&i.Reference,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getCreditAccountByID = `-- name: GetCreditAccountByID :one
SELECT id, user_id, balance, reserved, version, created_at, updated_at FROM credit_accounts WHERE id = $1
`

func (q *Queries) GetCreditAccountByID(ctx context.Context, id string) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, getCreditAccountByID, id)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditAccountByUserID = `-- name: GetCreditAccountByUserID :one
SELECT id, user_id, balance, reserved, version, created_at, updated_at FROM credit_accounts WHERE user_id = $1
`

func (q *Queries) GetCreditAccountByUserID(ctx context.Context, userID string) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, getCreditAccountByUserID, userID)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditAccountForUpdate = `-- name: GetCreditAccountForUpdate :one
SELECT id, user_id, balance, reserved, version, created_at, updated_at FROM credit_accounts WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetCreditAccountForUpdate(ctx context.Context, userID string) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, getCreditAccountForUpdate, userID)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditReservationByReference = `-- name: GetCreditReservationByReference :one
SELECT id, account_id, amount, operation, reference, status, expires_at, created_at, updated_at FROM credit_reservations WHERE reference = $1
`

func (q *Queries) GetCreditReservationByReference(ctx context.Context, reference string) (CreditReservation, error) {
	row := q.db.QueryRow(ctx, getCreditReservationByReference, reference)
	var i CreditReservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Operation,
		&i.Reference,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditTransactionByReference = `-- name: GetCreditTransactionByReference :one
SELECT id, account_id, type, amount, operation, status, reference, metadata, created_at FROM credit_transactions WHERE reference = $1
`

func (q *Queries) GetCreditTransactionByReference(ctx context.Context, reference *string) (CreditTransaction, error) {
	row := q.db.QueryRow(ctx, getCreditTransactionByReference, reference)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.Operation,
		&i.Status,
		&i.Reference,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getGenerationCost = `-- name: GetGenerationCost :one
SELECT operation, name, credits, is_active, updated_at FROM generation_costs WHERE operation = $1
`

func (q *Queries) GetGenerationCost(ctx context.Context, operation string) (GenerationCost, error) {
	row := q.db.QueryRow(ctx, getGenerationCost, operation)
	var i GenerationCost
	err := row.Scan(
		&i.Operation,
		&i.Name,
		&i.Credits,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditTransactions = `-- name: ListCreditTransactions :many
SELECT id, account_id, type, amount, operation, status, reference, metadata, created_at FROM credit_transactions
WHERE account_id = $1
  AND ($2::text = '' OR type = $2::text)
  AND ($3::text = '' OR operation = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListCreditTransactionsParams struct {
	AccountID       string `json:"account_id"`
	TypeFilter      string `json:"type_filter"`
	OperationFilter string `json:"operation_filter"`
	Offset          int32  `json:"offset"`
	Limit           int32  `json:"limit"`
}

func (q *Queries) ListCreditTransactions(ctx context.Context, arg ListCreditTransactionsParams) ([]CreditTransaction, error) {
	rows, err := q.db.Query(ctx, listCreditTransactions,
		arg.AccountID,
		arg.TypeFilter,
		arg.OperationFilter,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditTransaction
	for rows.Next() {
		var i CreditTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.Operation,
			&i.Status,
			&i.Reference,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationCosts = `-- name: ListGenerationCosts :many
SELECT operation, name, credits, is_active, updated_at FROM generation_costs WHERE is_active = true ORDER BY operation
`

func (q *Queries) ListGenerationCosts(ctx context.Context) ([]GenerationCost, error) {
	rows, err := q.db.Query(ctx, listGenerationCosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationCost
	for rows.Next() {
		var i GenerationCost
		if err := rows.Scan(
			&i.Operation,
			&i.Name,
			&i.Credits,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtractCredits = `-- name: SubtractCredits :one
UPDATE credit_accounts
SET balance = balance - $2, version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, user_id, balance, reserved, version, created_at, updated_at
`

type SubtractCreditsParams struct {
	ID      string `json:"id"`
	Balance int32  `json:"balance"`
}

func (q *Queries) SubtractCredits(ctx context.Context, arg SubtractCreditsParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, subtractCredits, arg.ID, arg.Balance)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const subtractReserved = `-- name: SubtractReserved :one
UPDATE credit_accounts
SET reserved = reserved - $2, version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, user_id, balance, reserved, version, created_at, updated_at
`

type SubtractReservedParams struct {
	ID       string `json:"id"`
	Reserved int32  `json:"reserved"`
}

func (q *Queries) SubtractReserved(ctx context.Context, arg SubtractReservedParams) (CreditAccount, error) {
	row := q.db.QueryRow(ctx, subtractReserved, arg.ID, arg.Reserved)
	var i CreditAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Reserved,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumCreditTransactionsByTypeSince = `-- name: SumCreditTransactionsByTypeSince :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM credit_transactions
WHERE account_id = $1 AND type = $2 AND status = 'completed' AND created_at >= $3
`

type SumCreditTransactionsByTypeSinceParams struct {
	AccountID string    `json:"account_id"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) SumCreditTransactionsByTypeSince(ctx context.Context, arg SumCreditTransactionsByTypeSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumCreditTransactionsByTypeSince, arg.AccountID, arg.Type, arg.CreatedAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateCreditReservationStatus = `-- name: UpdateCreditReservationStatus :one
UPDATE credit_reservations
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, account_id, amount, operation, reference, status, expires_at, created_at, updated_at
`

type UpdateCreditReservationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCreditReservationStatus(ctx context.Context, arg UpdateCreditReservationStatusParams) (CreditReservation, error) {
	row := q.db.QueryRow(ctx, updateCreditReservationStatus, arg.ID, arg.Status)
	var i CreditReservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Operation,
		&i.Reference,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
