// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"
)

const countUserConversations = `-- name: CountUserConversations :one
SELECT count(*) FROM conversations WHERE user_id = $1
`

func (q *Queries) CountUserConversations(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserConversations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserJobsByStatus = `-- name: CountUserJobsByStatus :many
SELECT status, count(*) AS total FROM generation_jobs WHERE user_id = $1 GROUP BY status
`

type CountUserJobsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountUserJobsByStatus(ctx context.Context, userID string) ([]CountUserJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countUserJobsByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUserJobsByStatusRow
	for rows.Next() {
		var i CountUserJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserOpenTickets = `-- name: CountUserOpenTickets :one
SELECT count(*) FROM support_tickets WHERE user_id = $1 AND status = 'open'
`

func (q *Queries) CountUserOpenTickets(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserOpenTickets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserProjects = `-- name: CountUserProjects :one
SELECT count(*) FROM projects WHERE user_id = $1
`

func (q *Queries) CountUserProjects(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserProjects, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCreditAccount = `-- name: GetUserCreditAccount :one
SELECT COALESCE(balance, 0)::bigint AS balance, COALESCE(reserved, 0)::bigint AS reserved
FROM credit_accounts WHERE user_id = $1
`

type GetUserCreditAccountRow struct {
	Balance  int64 `json:"balance"`
	Reserved int64 `json:"reserved"`
}

func (q *Queries) GetUserCreditAccount(ctx context.Context, userID string) (GetUserCreditAccountRow, error) {
	row := q.db.QueryRow(ctx, getUserCreditAccount, userID)
	var i GetUserCreditAccountRow
	err := row.Scan(&i.Balance, &i.Reserved)
	return i, err
}

const sumUserCreditsUsedSince = `-- name: SumUserCreditsUsedSince :one
SELECT COALESCE(sum(t.amount), 0)::bigint AS total
FROM credit_transactions t
JOIN credit_accounts a ON a.id = t.account_id
WHERE a.user_id = $1
  AND t.type = 'debit'
  AND t.status = 'completed'
  AND t.created_at >= $2
`

type SumUserCreditsUsedSinceParams struct {
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) SumUserCreditsUsedSince(ctx context.Context, arg SumUserCreditsUsedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumUserCreditsUsedSince, arg.UserID, arg.CreatedAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const userCreditsPerDay = `-- name: UserCreditsPerDay :many
SELECT date_trunc('day', t.created_at)::timestamptz AS day, COALESCE(sum(t.amount), 0)::bigint AS total
FROM credit_transactions t
JOIN credit_accounts a ON a.id = t.account_id
WHERE a.user_id = $1
  AND t.type = 'debit'
  AND t.status = 'completed'
  AND t.created_at >= $2
GROUP BY day
ORDER BY day
`

type UserCreditsPerDayParams struct {
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserCreditsPerDayRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) UserCreditsPerDay(ctx context.Context, arg UserCreditsPerDayParams) ([]UserCreditsPerDayRow, error) {
	rows, err := q.db.Query(ctx, userCreditsPerDay, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCreditsPerDayRow
	for rows.Next() {
		var i UserCreditsPerDayRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userProjectsPerWeek = `-- name: UserProjectsPerWeek :many
SELECT date_trunc('week', created_at)::timestamptz AS week, count(*)::bigint AS total
FROM projects
WHERE user_id = $1
  AND created_at >= $2
GROUP BY week
ORDER BY week
`

type UserProjectsPerWeekParams struct {
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserProjectsPerWeekRow struct {
	Week  time.Time `json:"week"`
	Total int64     `json:"total"`
}

func (q *Queries) UserProjectsPerWeek(ctx context.Context, arg UserProjectsPerWeekParams) ([]UserProjectsPerWeekRow, error) {
	rows, err := q.db.Query(ctx, userProjectsPerWeek, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProjectsPerWeekRow
	for rows.Next() {
		var i UserProjectsPerWeekRow
		if err := rows.Scan(&i.Week, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
