// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idea_messages.sql

package db

import (
	"context"
)

const createIdeaMessage = `-- name: CreateIdeaMessage :one
INSERT INTO idea_messages (idea_id, user_id, role, content)
VALUES ($1, $2, $3, $4)
RETURNING id, idea_id, user_id, role, content, created_at
`

type CreateIdeaMessageParams struct {
	IdeaID  string `json:"idea_id"`
	UserID  string `json:"user_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) CreateIdeaMessage(ctx context.Context, arg CreateIdeaMessageParams) (IdeaMessage, error) {
	row := q.db.QueryRow(ctx, createIdeaMessage,
		arg.IdeaID,
		arg.UserID,
		arg.Role,
		arg.Content,
	)
	var i IdeaMessage
	err := row.Scan(
		&i.ID,
		&i.IdeaID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listIdeaMessages = `-- name: ListIdeaMessages :many
SELECT id, idea_id, user_id, role, content, created_at FROM idea_messages WHERE idea_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListIdeaMessages(ctx context.Context, ideaID string) ([]IdeaMessage, error) {
	rows, err := q.db.Query(ctx, listIdeaMessages, ideaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdeaMessage
	for rows.Next() {
		var i IdeaMessage
		if err := rows.Scan(
			&i.ID,
			&i.IdeaID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
