// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ideas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdea = `-- name: CreateIdea :one
INSERT INTO product_ideas (user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle, is_selected, created_at
`

type CreateIdeaParams struct {
	UserID           string      `json:"user_id"`
	OpportunityID    pgtype.UUID `json:"opportunity_id"`
	Title            string      `json:"title"`
	Subtitle         string      `json:"subtitle"`
	Audience         string      `json:"audience"`
	Problem          string      `json:"problem"`
	Promise          string      `json:"promise"`
	Format           string      `json:"format"`
	EstimatedPrice   string      `json:"estimated_price"`
	Difficulty       string      `json:"difficulty"`
	MarketEvidence   string      `json:"market_evidence"`
	WhyNow           string      `json:"why_now"`
	CompetitiveAngle string      `json:"competitive_angle"`
}

func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (ProductIdea, error) {
	row := q.db.QueryRow(ctx, createIdea,
		arg.UserID,
		arg.OpportunityID,
		arg.Title,
		arg.Subtitle,
		arg.Audience,
		arg.Problem,
		arg.Promise,
		arg.Format,
		arg.EstimatedPrice,
		arg.Difficulty,
		arg.MarketEvidence,
		arg.WhyNow,
		arg.CompetitiveAngle,
	)
	var i ProductIdea
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.Title,
		&i.Subtitle,
		&i.Audience,
		&i.Problem,
		&i.Promise,
		&i.Format,
		&i.EstimatedPrice,
		&i.Difficulty,
		&i.MarketEvidence,
		&i.WhyNow,
		&i.CompetitiveAngle,
		&i.IsSelected,
		&i.CreatedAt,
	)
	return i, err
}

const getIdea = `-- name: GetIdea :one
SELECT id, user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle, is_selected, created_at FROM product_ideas WHERE id = $1 AND user_id = $2
`

type GetIdeaParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetIdea(ctx context.Context, arg GetIdeaParams) (ProductIdea, error) {
	row := q.db.QueryRow(ctx, getIdea, arg.ID, arg.UserID)
	var i ProductIdea
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.Title,
		&i.Subtitle,
		&i.Audience,
		&i.Problem,
		&i.Promise,
		&i.Format,
		&i.EstimatedPrice,
		&i.Difficulty,
		&i.MarketEvidence,
		&i.WhyNow,
		&i.CompetitiveAngle,
		&i.IsSelected,
		&i.CreatedAt,
	)
	return i, err
}

const listIdeasByOpportunity = `-- name: ListIdeasByOpportunity :many
SELECT id, user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle, is_selected, created_at FROM product_ideas WHERE user_id = $1 AND opportunity_id = $2 ORDER BY created_at ASC
`

type ListIdeasByOpportunityParams struct {
	UserID        string      `json:"user_id"`
	OpportunityID pgtype.UUID `json:"opportunity_id"`
}

func (q *Queries) ListIdeasByOpportunity(ctx context.Context, arg ListIdeasByOpportunityParams) ([]ProductIdea, error) {
	rows, err := q.db.Query(ctx, listIdeasByOpportunity, arg.UserID, arg.OpportunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductIdea
	for rows.Next() {
		var i ProductIdea
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpportunityID,
			&i.Title,
			&i.Subtitle,
			&i.Audience,
			&i.Problem,
			&i.Promise,
			&i.Format,
			&i.EstimatedPrice,
			&i.Difficulty,
			&i.MarketEvidence,
			&i.WhyNow,
			&i.CompetitiveAngle,
			&i.IsSelected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdeasByUser = `-- name: ListIdeasByUser :many
SELECT id, user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle, is_selected, created_at FROM product_ideas WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListIdeasByUser(ctx context.Context, userID string) ([]ProductIdea, error) {
	rows, err := q.db.Query(ctx, listIdeasByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductIdea
	for rows.Next() {
		var i ProductIdea
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpportunityID,
			&i.Title,
			&i.Subtitle,
			&i.Audience,
			&i.Problem,
			&i.Promise,
			&i.Format,
			&i.EstimatedPrice,
			&i.Difficulty,
			&i.MarketEvidence,
			&i.WhyNow,
			&i.CompetitiveAngle,
			&i.IsSelected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectIdea = `-- name: SelectIdea :one
UPDATE product_ideas SET is_selected = true WHERE id = $1 AND user_id = $2 RETURNING id, user_id, opportunity_id, title, subtitle, audience, problem, promise, format, estimated_price, difficulty, market_evidence, why_now, competitive_angle, is_selected, created_at
`

type SelectIdeaParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SelectIdea(ctx context.Context, arg SelectIdeaParams) (ProductIdea, error) {
	row := q.db.QueryRow(ctx, selectIdea, arg.ID, arg.UserID)
	var i ProductIdea
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.Title,
		&i.Subtitle,
		&i.Audience,
		&i.Problem,
		&i.Promise,
		&i.Format,
		&i.EstimatedPrice,
		&i.Difficulty,
		&i.MarketEvidence,
		&i.WhyNow,
		&i.CompetitiveAngle,
		&i.IsSelected,
		&i.CreatedAt,
	)
	return i, err
}

const unselectIdea = `-- name: UnselectIdea :exec
UPDATE product_ideas SET is_selected = false WHERE id = $1 AND user_id = $2
`

type UnselectIdeaParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UnselectIdea(ctx context.Context, arg UnselectIdeaParams) error {
	_, err := q.db.Exec(ctx, unselectIdea, arg.ID, arg.UserID)
	return err
}
