// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeJob = `-- name: CompleteJob :one
UPDATE generation_jobs
SET status = 'completed', result = $2, cost = $3, completed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, user_id, project_id, opportunity_id, kind, status, error, cost, result, created_at, updated_at, completed_at
`

type CompleteJobParams struct {
	ID     string `json:"id"`
	Result []byte `json:"result"`
	Cost   int32  `json:"cost"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.ID, arg.Result, arg.Cost)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.Cost,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO generation_jobs (user_id, project_id, opportunity_id, kind, status, cost)
VALUES ($1, $2, $3, $4, 'pending', $5)
RETURNING id, user_id, project_id, opportunity_id, kind, status, error, cost, result, created_at, updated_at, completed_at
`

type CreateJobParams struct {
	UserID        string      `json:"user_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	OpportunityID pgtype.UUID `json:"opportunity_id"`
	Kind          string      `json:"kind"`
	Cost          int32       `json:"cost"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.ProjectID,
		arg.OpportunityID,
		arg.Kind,
		arg.Cost,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.Cost,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE generation_jobs
SET status = 'failed', error = $2, updated_at = now(), completed_at = now()
WHERE id = $1
RETURNING id, user_id, project_id, opportunity_id, kind, status, error, cost, result, created_at, updated_at, completed_at
`

type FailJobParams struct {
	ID    string  `json:"id"`
	Error *string `json:"error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, failJob, arg.ID, arg.Error)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.Cost,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, user_id, project_id, opportunity_id, kind, status, error, cost, result, created_at, updated_at, completed_at FROM generation_jobs WHERE id = $1 AND user_id = $2
`

type GetJobParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.UserID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.Cost,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listJobsByProject = `-- name: ListJobsByProject :many
SELECT id, user_id, project_id, opportunity_id, kind, status, error, cost, result, created_at, updated_at, completed_at FROM generation_jobs WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListJobsByProject(ctx context.Context, projectID pgtype.UUID) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listJobsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationJob
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.OpportunityID,
			&i.Kind,
			&i.Status,
			&i.Error,
			&i.Cost,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE generation_jobs SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, project_id, opportunity_id, kind, status, error, cost, result, created_at, updated_at, completed_at
`

type UpdateJobStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.Cost,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
