// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markets.sql

package db

import (
	"context"
)

const listMarkets = `-- name: ListMarkets :many
SELECT id, code, name, currency, language, is_active FROM markets WHERE is_active = true ORDER BY name
`

func (q *Queries) ListMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.Query(ctx, listMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Currency,
			&i.Language,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
