// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	ProjectID   string    `json:"project_id"`
	Kind        string    `json:"kind"`
	StorageKey  string    `json:"storage_key"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int32     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
}

type AuditLog struct {
	ID        string      `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Entity    string      `json:"entity"`
	EntityID  *string     `json:"entity_id"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}

type Conversation struct {
	ID            string      `json:"id"`
	UserID        string      `json:"user_id"`
	Title         string      `json:"title"`
	Status        string      `json:"status"`
	OpportunityID pgtype.UUID `json:"opportunity_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type ConversationMessage struct {
	ID             string    `json:"id"`
	ConversationID string    `json:"conversation_id"`
	UserID         string    `json:"user_id"`
	Role           string    `json:"role"`
	Content        string    `json:"content"`
	Payload        []byte    `json:"payload"`
	CreatedAt      time.Time `json:"created_at"`
}

type CreditAccount struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Balance   int32     `json:"balance"`
	Reserved  int32     `json:"reserved"`
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CreditReservation struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	Amount    int32     `json:"amount"`
	Operation string    `json:"operation"`
	Reference string    `json:"reference"`
	Status    string    `json:"status"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CreditTransaction struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	Type      string    `json:"type"`
	Amount    int32     `json:"amount"`
	Operation string    `json:"operation"`
	Status    string    `json:"status"`
	Reference *string   `json:"reference"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type GenerationCost struct {
	Operation string    `json:"operation"`
	Name      string    `json:"name"`
	Credits   int32     `json:"credits"`
	IsActive  bool      `json:"is_active"`
	UpdatedAt time.Time `json:"updated_at"`
}

type GenerationJob struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	OpportunityID pgtype.UUID        `json:"opportunity_id"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	Error         *string            `json:"error"`
	Cost          int32              `json:"cost"`
	Result        []byte             `json:"result"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ResearchID    pgtype.UUID        `json:"research_id"`
	IdeaID        pgtype.UUID        `json:"idea_id"`
	Params        []byte             `json:"params"`
}

type IdeaMessage struct {
	ID        string    `json:"id"`
	IdeaID    string    `json:"idea_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Market struct {
	ID       string `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Language string `json:"language"`
	IsActive bool   `json:"is_active"`
}

type Opportunity struct {
	ID         string      `json:"id"`
	Title      string      `json:"title"`
	Summary    string      `json:"summary"`
	Country    string      `json:"country"`
	Sector     string      `json:"sector"`
	Language   string      `json:"language"`
	Difficulty string      `json:"difficulty"`
	Signal     string      `json:"signal"`
	Score      int32       `json:"score"`
	Scores     []byte      `json:"scores"`
	Evidence   []byte      `json:"evidence"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	UserID     pgtype.UUID `json:"user_id"`
	ResearchID pgtype.UUID `json:"research_id"`
}

type Organization struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Payment struct {
	ID                string      `json:"id"`
	UserID            string      `json:"user_id"`
	PlanID            pgtype.UUID `json:"plan_id"`
	AmountMinor       int32       `json:"amount_minor"`
	Currency          string      `json:"currency"`
	Provider          string      `json:"provider"`
	Status            string      `json:"status"`
	IdempotencyKey    string      `json:"idempotency_key"`
	ProviderReference *string     `json:"provider_reference"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type Plan struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Credits    int32     `json:"credits"`
	PriceMinor int32     `json:"price_minor"`
	Currency   string    `json:"currency"`
	SortOrder  int32     `json:"sort_order"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
}

type ProductIdea struct {
	ID               string      `json:"id"`
	UserID           string      `json:"user_id"`
	OpportunityID    pgtype.UUID `json:"opportunity_id"`
	Title            string      `json:"title"`
	Subtitle         string      `json:"subtitle"`
	Audience         string      `json:"audience"`
	Problem          string      `json:"problem"`
	Promise          string      `json:"promise"`
	Format           string      `json:"format"`
	EstimatedPrice   string      `json:"estimated_price"`
	Difficulty       string      `json:"difficulty"`
	MarketEvidence   string      `json:"market_evidence"`
	WhyNow           string      `json:"why_now"`
	CompetitiveAngle string      `json:"competitive_angle"`
	IsSelected       bool        `json:"is_selected"`
	CreatedAt        time.Time   `json:"created_at"`
	Hook             string      `json:"hook"`
	Explanation      string      `json:"explanation"`
	Status           string      `json:"status"`
	UpdatedAt        time.Time   `json:"updated_at"`
	ConversationID   pgtype.UUID `json:"conversation_id"`
}

type Project struct {
	ID              string      `json:"id"`
	UserID          string      `json:"user_id"`
	OpportunityID   pgtype.UUID `json:"opportunity_id"`
	IdeaID          pgtype.UUID `json:"idea_id"`
	Title           string      `json:"title"`
	Status          string      `json:"status"`
	CreditsConsumed int32       `json:"credits_consumed"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Config          []byte      `json:"config"`
}

type RefreshToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  time.Time          `json:"created_at"`
}

type ResearchRequest struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Query     string    `json:"query"`
	Sector    string    `json:"sector"`
	Markets   []byte    `json:"markets"`
	Language  string    `json:"language"`
	Status    string    `json:"status"`
	Error     *string   `json:"error"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SavedOpportunity struct {
	UserID        string    `json:"user_id"`
	OpportunityID string    `json:"opportunity_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type SupportTicket struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Subject   string    `json:"subject"`
	Message   string    `json:"message"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SupportTicketMessage struct {
	ID        string    `json:"id"`
	TicketID  string    `json:"ticket_id"`
	AuthorID  string    `json:"author_id"`
	Content   string    `json:"content"`
	IsAdmin   bool      `json:"is_admin"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    *string            `json:"password_hash"`
	FullName        string             `json:"full_name"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	AvatarUrl       *string            `json:"avatar_url"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Role            string             `json:"role"`
}

type UserPreference struct {
	UserID    string    `json:"user_id"`
	Language  string    `json:"language"`
	Theme     string    `json:"theme"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
