// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        string      `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Entity    string      `json:"entity"`
	EntityID  *string     `json:"entity_id"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}

type CreditAccount struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Balance   int32     `json:"balance"`
	Reserved  int32     `json:"reserved"`
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CreditReservation struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	Amount    int32     `json:"amount"`
	Operation string    `json:"operation"`
	Reference string    `json:"reference"`
	Status    string    `json:"status"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CreditTransaction struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	Type      string    `json:"type"`
	Amount    int32     `json:"amount"`
	Operation string    `json:"operation"`
	Status    string    `json:"status"`
	Reference *string   `json:"reference"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type GenerationCost struct {
	Operation string    `json:"operation"`
	Name      string    `json:"name"`
	Credits   int32     `json:"credits"`
	IsActive  bool      `json:"is_active"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Market struct {
	ID       string `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Language string `json:"language"`
	IsActive bool   `json:"is_active"`
}

type Opportunity struct {
	ID         string    `json:"id"`
	Title      string    `json:"title"`
	Summary    string    `json:"summary"`
	Country    string    `json:"country"`
	Sector     string    `json:"sector"`
	Language   string    `json:"language"`
	Difficulty string    `json:"difficulty"`
	Signal     string    `json:"signal"`
	Score      int32     `json:"score"`
	Scores     []byte    `json:"scores"`
	Evidence   []byte    `json:"evidence"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Organization struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Payment struct {
	ID                string      `json:"id"`
	UserID            string      `json:"user_id"`
	PlanID            pgtype.UUID `json:"plan_id"`
	AmountMinor       int32       `json:"amount_minor"`
	Currency          string      `json:"currency"`
	Provider          string      `json:"provider"`
	Status            string      `json:"status"`
	IdempotencyKey    string      `json:"idempotency_key"`
	ProviderReference *string     `json:"provider_reference"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type Plan struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Credits    int32     `json:"credits"`
	PriceMinor int32     `json:"price_minor"`
	Currency   string    `json:"currency"`
	SortOrder  int32     `json:"sort_order"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  time.Time          `json:"created_at"`
}

type SavedOpportunity struct {
	UserID        string    `json:"user_id"`
	OpportunityID string    `json:"opportunity_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    *string            `json:"password_hash"`
	FullName        string             `json:"full_name"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	AvatarUrl       *string            `json:"avatar_url"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}
