// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opportunities.sql

package db

import (
	"context"
)

const countOpportunities = `-- name: CountOpportunities :one
SELECT count(*) FROM opportunities
WHERE ($1::text = '' OR country = $1::text)
  AND ($2::text = '' OR sector = $2::text)
  AND ($3::text = '' OR difficulty = $3::text)
  AND ($4::text = '' OR title ILIKE '%' || $4::text || '%')
`

type CountOpportunitiesParams struct {
	Country    string `json:"country"`
	Sector     string `json:"sector"`
	Difficulty string `json:"difficulty"`
	Query      string `json:"query"`
}

func (q *Queries) CountOpportunities(ctx context.Context, arg CountOpportunitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpportunities,
		arg.Country,
		arg.Sector,
		arg.Difficulty,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOpportunity = `-- name: GetOpportunity :one
SELECT id, title, summary, country, sector, language, difficulty, signal, score, scores, evidence, created_at, updated_at FROM opportunities WHERE id = $1
`

func (q *Queries) GetOpportunity(ctx context.Context, id string) (Opportunity, error) {
	row := q.db.QueryRow(ctx, getOpportunity, id)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Country,
		&i.Sector,
		&i.Language,
		&i.Difficulty,
		&i.Signal,
		&i.Score,
		&i.Scores,
		&i.Evidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctCountries = `-- name: ListDistinctCountries :many
SELECT DISTINCT country FROM opportunities WHERE country <> '' ORDER BY country
`

func (q *Queries) ListDistinctCountries(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var country string
		if err := rows.Scan(&country); err != nil {
			return nil, err
		}
		items = append(items, country)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSectors = `-- name: ListDistinctSectors :many
SELECT DISTINCT sector FROM opportunities WHERE sector <> '' ORDER BY sector
`

func (q *Queries) ListDistinctSectors(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctSectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sector string
		if err := rows.Scan(&sector); err != nil {
			return nil, err
		}
		items = append(items, sector)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpportunities = `-- name: ListOpportunities :many
SELECT id, title, summary, country, sector, language, difficulty, signal, score, scores, evidence, created_at, updated_at FROM opportunities
WHERE ($1::text = '' OR country = $1::text)
  AND ($2::text = '' OR sector = $2::text)
  AND ($3::text = '' OR difficulty = $3::text)
  AND ($4::text = '' OR title ILIKE '%' || $4::text || '%')
ORDER BY score DESC, created_at DESC
LIMIT $6 OFFSET $5
`

type ListOpportunitiesParams struct {
	Country    string `json:"country"`
	Sector     string `json:"sector"`
	Difficulty string `json:"difficulty"`
	Query      string `json:"query"`
	Offset     int32  `json:"offset"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error) {
	rows, err := q.db.Query(ctx, listOpportunities,
		arg.Country,
		arg.Sector,
		arg.Difficulty,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Opportunity
	for rows.Next() {
		var i Opportunity
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Country,
			&i.Sector,
			&i.Language,
			&i.Difficulty,
			&i.Signal,
			&i.Score,
			&i.Scores,
			&i.Evidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedOpportunityIDs = `-- name: ListSavedOpportunityIDs :many
SELECT opportunity_id FROM saved_opportunities WHERE user_id = $1
`

func (q *Queries) ListSavedOpportunityIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSavedOpportunityIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var opportunity_id string
		if err := rows.Scan(&opportunity_id); err != nil {
			return nil, err
		}
		items = append(items, opportunity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOpportunity = `-- name: SaveOpportunity :exec
INSERT INTO saved_opportunities (user_id, opportunity_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SaveOpportunityParams struct {
	UserID        string `json:"user_id"`
	OpportunityID string `json:"opportunity_id"`
}

func (q *Queries) SaveOpportunity(ctx context.Context, arg SaveOpportunityParams) error {
	_, err := q.db.Exec(ctx, saveOpportunity, arg.UserID, arg.OpportunityID)
	return err
}

const unsaveOpportunity = `-- name: UnsaveOpportunity :exec
DELETE FROM saved_opportunities WHERE user_id = $1 AND opportunity_id = $2
`

type UnsaveOpportunityParams struct {
	UserID        string `json:"user_id"`
	OpportunityID string `json:"opportunity_id"`
}

func (q *Queries) UnsaveOpportunity(ctx context.Context, arg UnsaveOpportunityParams) error {
	_, err := q.db.Exec(ctx, unsaveOpportunity, arg.UserID, arg.OpportunityID)
	return err
}
