// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
)

const listPlans = `-- name: ListPlans :many
SELECT id, name, credits, price_minor, currency, sort_order, is_active, created_at FROM plans WHERE is_active = true ORDER BY sort_order
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Credits,
			&i.PriceMinor,
			&i.Currency,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
