// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package db

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, language, theme, created_at, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserPreferences = `-- name: InsertUserPreferences :one
INSERT INTO user_preferences (user_id, language, theme)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, language, theme, created_at, updated_at
`

type InsertUserPreferencesParams struct {
	UserID   string `json:"user_id"`
	Language string `json:"language"`
	Theme    string `json:"theme"`
}

func (q *Queries) InsertUserPreferences(ctx context.Context, arg InsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, insertUserPreferences, arg.UserID, arg.Language, arg.Theme)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences
SET language = $2, theme = $3, updated_at = now()
WHERE user_id = $1
RETURNING user_id, language, theme, created_at, updated_at
`

type UpdateUserPreferencesParams struct {
	UserID   string `json:"user_id"`
	Language string `json:"language"`
	Theme    string `json:"theme"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences, arg.UserID, arg.Language, arg.Theme)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.Theme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
