// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectCredits = `-- name: AddProjectCredits :one
UPDATE projects SET credits_consumed = credits_consumed + $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, opportunity_id, idea_id, title, status, credits_consumed, created_at, updated_at
`

type AddProjectCreditsParams struct {
	ID              string `json:"id"`
	CreditsConsumed int32  `json:"credits_consumed"`
}

func (q *Queries) AddProjectCredits(ctx context.Context, arg AddProjectCreditsParams) (Project, error) {
	row := q.db.QueryRow(ctx, addProjectCredits, arg.ID, arg.CreditsConsumed)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.IdeaID,
		&i.Title,
		&i.Status,
		&i.CreditsConsumed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, opportunity_id, idea_id, title, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, opportunity_id, idea_id, title, status, credits_consumed, created_at, updated_at
`

type CreateProjectParams struct {
	UserID        string      `json:"user_id"`
	OpportunityID pgtype.UUID `json:"opportunity_id"`
	IdeaID        pgtype.UUID `json:"idea_id"`
	Title         string      `json:"title"`
	Status        string      `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.OpportunityID,
		arg.IdeaID,
		arg.Title,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.IdeaID,
		&i.Title,
		&i.Status,
		&i.CreditsConsumed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, opportunity_id, idea_id, title, status, credits_consumed, created_at, updated_at FROM projects WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.IdeaID,
		&i.Title,
		&i.Status,
		&i.CreditsConsumed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, opportunity_id, idea_id, title, status, credits_consumed, created_at, updated_at FROM projects WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpportunityID,
			&i.IdeaID,
			&i.Title,
			&i.Status,
			&i.CreditsConsumed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects SET status = $2, updated_at = now() WHERE id = $1 AND user_id = $3 RETURNING id, user_id, opportunity_id, idea_id, title, status, credits_consumed, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus, arg.ID, arg.Status, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OpportunityID,
		&i.IdeaID,
		&i.Title,
		&i.Status,
		&i.CreditsConsumed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
