// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddCredits(ctx context.Context, arg AddCreditsParams) (CreditAccount, error)
	AddReserved(ctx context.Context, arg AddReservedParams) (CreditAccount, error)
	CountCreditTransactions(ctx context.Context, arg CountCreditTransactionsParams) (int64, error)
	CountOpportunities(ctx context.Context, arg CountOpportunitiesParams) (int64, error)
	CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreditAccount, error)
	CreateCreditReservation(ctx context.Context, arg CreateCreditReservationParams) (CreditReservation, error)
	CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error)
	GetCreditAccountByID(ctx context.Context, id string) (CreditAccount, error)
	GetCreditAccountByUserID(ctx context.Context, userID string) (CreditAccount, error)
	GetCreditAccountForUpdate(ctx context.Context, userID string) (CreditAccount, error)
	GetCreditReservationByReference(ctx context.Context, reference string) (CreditReservation, error)
	GetCreditTransactionByReference(ctx context.Context, reference *string) (CreditTransaction, error)
	GetGenerationCost(ctx context.Context, operation string) (GenerationCost, error)
	GetOpportunity(ctx context.Context, id string) (Opportunity, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListCreditTransactions(ctx context.Context, arg ListCreditTransactionsParams) ([]CreditTransaction, error)
	ListDistinctCountries(ctx context.Context) ([]string, error)
	ListDistinctSectors(ctx context.Context) ([]string, error)
	ListGenerationCosts(ctx context.Context) ([]GenerationCost, error)
	ListMarkets(ctx context.Context) ([]Market, error)
	ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListSavedOpportunityIDs(ctx context.Context, userID string) ([]string, error)
	SaveOpportunity(ctx context.Context, arg SaveOpportunityParams) error
	SubtractCredits(ctx context.Context, arg SubtractCreditsParams) (CreditAccount, error)
	SubtractReserved(ctx context.Context, arg SubtractReservedParams) (CreditAccount, error)
	SumCreditTransactionsByTypeSince(ctx context.Context, arg SumCreditTransactionsByTypeSinceParams) (int64, error)
	UnsaveOpportunity(ctx context.Context, arg UnsaveOpportunityParams) error
	UpdateCreditReservationStatus(ctx context.Context, arg UpdateCreditReservationStatusParams) (CreditReservation, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
