// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCredits(ctx context.Context, arg AddCreditsParams) (CreditAccount, error)
	AddProjectCredits(ctx context.Context, arg AddProjectCreditsParams) (Project, error)
	AddReserved(ctx context.Context, arg AddReservedParams) (CreditAccount, error)
	CompleteJob(ctx context.Context, arg CompleteJobParams) (GenerationJob, error)
	CountCreditTransactions(ctx context.Context, arg CountCreditTransactionsParams) (int64, error)
	CountOpportunities(ctx context.Context, arg CountOpportunitiesParams) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateConversation(ctx context.Context, userID string) (Conversation, error)
	CreateConversationMessage(ctx context.Context, arg CreateConversationMessageParams) (ConversationMessage, error)
	CreateCreditAccount(ctx context.Context, arg CreateCreditAccountParams) (CreditAccount, error)
	CreateCreditReservation(ctx context.Context, arg CreateCreditReservationParams) (CreditReservation, error)
	CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error)
	CreateIdea(ctx context.Context, arg CreateIdeaParams) (ProductIdea, error)
	CreateIdeaMessage(ctx context.Context, arg CreateIdeaMessageParams) (IdeaMessage, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (GenerationJob, error)
	CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateResearchRequest(ctx context.Context, arg CreateResearchRequestParams) (ResearchRequest, error)
	FailJob(ctx context.Context, arg FailJobParams) (GenerationJob, error)
	GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error)
	GetCreditAccountByID(ctx context.Context, id string) (CreditAccount, error)
	GetCreditAccountByUserID(ctx context.Context, userID string) (CreditAccount, error)
	GetCreditAccountForUpdate(ctx context.Context, userID string) (CreditAccount, error)
	GetCreditReservationByReference(ctx context.Context, reference string) (CreditReservation, error)
	GetCreditTransactionByReference(ctx context.Context, reference *string) (CreditTransaction, error)
	GetGenerationCost(ctx context.Context, operation string) (GenerationCost, error)
	GetIdea(ctx context.Context, arg GetIdeaParams) (ProductIdea, error)
	GetJob(ctx context.Context, arg GetJobParams) (GenerationJob, error)
	GetOpportunity(ctx context.Context, id string) (Opportunity, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetResearchRequest(ctx context.Context, arg GetResearchRequestParams) (ResearchRequest, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPreferences(ctx context.Context, userID string) (UserPreference, error)
	InsertUserPreferences(ctx context.Context, arg InsertUserPreferencesParams) (UserPreference, error)
	ListAssetsByProject(ctx context.Context, projectID string) ([]Asset, error)
	ListConversationMessages(ctx context.Context, conversationID string) ([]ConversationMessage, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error)
	ListCreditTransactions(ctx context.Context, arg ListCreditTransactionsParams) ([]CreditTransaction, error)
	ListDistinctCountries(ctx context.Context) ([]string, error)
	ListDistinctSectors(ctx context.Context) ([]string, error)
	ListGenerationCosts(ctx context.Context) ([]GenerationCost, error)
	ListIdeaMessages(ctx context.Context, ideaID string) ([]IdeaMessage, error)
	ListIdeasByConversation(ctx context.Context, arg ListIdeasByConversationParams) ([]ProductIdea, error)
	ListIdeasByOpportunity(ctx context.Context, arg ListIdeasByOpportunityParams) ([]ProductIdea, error)
	ListIdeasByUser(ctx context.Context, userID string) ([]ProductIdea, error)
	ListJobsByProject(ctx context.Context, projectID pgtype.UUID) ([]GenerationJob, error)
	ListMarkets(ctx context.Context) ([]Market, error)
	ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListProjectsByUser(ctx context.Context, userID string) ([]Project, error)
	ListSavedOpportunityIDs(ctx context.Context, userID string) ([]string, error)
	SaveOpportunity(ctx context.Context, arg SaveOpportunityParams) error
	SelectIdea(ctx context.Context, arg SelectIdeaParams) (ProductIdea, error)
	SetConversationOpportunity(ctx context.Context, arg SetConversationOpportunityParams) (Conversation, error)
	SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) (Conversation, error)
	SetIdeaStatus(ctx context.Context, arg SetIdeaStatusParams) (ProductIdea, error)
	SubtractCredits(ctx context.Context, arg SubtractCreditsParams) (CreditAccount, error)
	SubtractReserved(ctx context.Context, arg SubtractReservedParams) (CreditAccount, error)
	SumCreditTransactionsByTypeSince(ctx context.Context, arg SumCreditTransactionsByTypeSinceParams) (int64, error)
	TouchConversation(ctx context.Context, id string) (Conversation, error)
	UnsaveOpportunity(ctx context.Context, arg UnsaveOpportunityParams) error
	UnselectIdea(ctx context.Context, arg UnselectIdeaParams) error
	UpdateCreditReservationStatus(ctx context.Context, arg UpdateCreditReservationStatusParams) (CreditReservation, error)
	UpdateIdeaContent(ctx context.Context, arg UpdateIdeaContentParams) (ProductIdea, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (GenerationJob, error)
	UpdateProjectConfig(ctx context.Context, arg UpdateProjectConfigParams) (Project, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error)
	UpdateResearchRequestStatus(ctx context.Context, arg UpdateResearchRequestStatusParams) (ResearchRequest, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
