// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: research.sql

package db

import (
	"context"
)

const createResearchRequest = `-- name: CreateResearchRequest :one
INSERT INTO research_requests (user_id, query, sector, markets, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, query, sector, markets, language, status, error, created_at, updated_at
`

type CreateResearchRequestParams struct {
	UserID   string `json:"user_id"`
	Query    string `json:"query"`
	Sector   string `json:"sector"`
	Markets  []byte `json:"markets"`
	Language string `json:"language"`
}

func (q *Queries) CreateResearchRequest(ctx context.Context, arg CreateResearchRequestParams) (ResearchRequest, error) {
	row := q.db.QueryRow(ctx, createResearchRequest,
		arg.UserID,
		arg.Query,
		arg.Sector,
		arg.Markets,
		arg.Language,
	)
	var i ResearchRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Sector,
		&i.Markets,
		&i.Language,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResearchRequest = `-- name: GetResearchRequest :one
SELECT id, user_id, query, sector, markets, language, status, error, created_at, updated_at FROM research_requests WHERE id = $1 AND user_id = $2
`

type GetResearchRequestParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetResearchRequest(ctx context.Context, arg GetResearchRequestParams) (ResearchRequest, error) {
	row := q.db.QueryRow(ctx, getResearchRequest, arg.ID, arg.UserID)
	var i ResearchRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Sector,
		&i.Markets,
		&i.Language,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResearchRequestStatus = `-- name: UpdateResearchRequestStatus :one
UPDATE research_requests SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, query, sector, markets, language, status, error, created_at, updated_at
`

type UpdateResearchRequestStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateResearchRequestStatus(ctx context.Context, arg UpdateResearchRequestStatusParams) (ResearchRequest, error) {
	row := q.db.QueryRow(ctx, updateResearchRequestStatus, arg.ID, arg.Status)
	var i ResearchRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.Sector,
		&i.Markets,
		&i.Language,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
